spring:
  sql:
    init:
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: root
    password: test

mybatis-plus:
  typeEnumsPackage: com.github.leheyue.test
  global-config:
    db-config:
      logic-delete-field: del
      logic-delete-value: true
      logic-not-delete-value: false
    banner: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 打印 mybatis plus join banner
mybatis-plus-join:
  banner: true
  sub-table-logic: true