#file: noinspection SpringBootApplicationYaml
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: root
    password: test
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/mpj_test
#    username: root
#    password: 123456
  sql:
    init:
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql

mybatis-plus:
  typeEnumsPackage: com.github.leheyue.test
  global-config:
    db-config:
      logic-delete-field: del
      logic-delete-value: true
      logic-not-delete-value: false
    banner: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mybatis-plus-join:
  # 打印 mybatis plus join banner
  banner: true
  sub-table-logic: true
  ms-cache: true
  logic-del-type: where
